// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qupcugmevajggaluopzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cGN1Z21ldmFqZ2dhbHVvcHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDg0MzAsImV4cCI6MjA3MzI4NDQzMH0.V39kB7Np-Vmd9Tfftsd_h-4AM8-UHhIaD0DPeYTZgB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});